Jenkinsfile, src/integrationTest/groovy/wooga/gradle/paket/pack/PaketPackIntegrationSpec.groovy, src/main/groovy/wooga/gradle/paket/base/PaketBasePlugin.groovy, src/main/groovy/wooga/gradle/paket/pack/PaketPackPlugin.groovy, src/test/groovy/wooga/gradle/paket/pack/PaketPackPluginSpec.groovy
Create all `paketPack` tasks when applying the plugin so users can refer
to the generated tasks at configuration time.
Adjust test specs
fixes #1
=> Fix paketPack task creation

src/integrationTest/groovy/wooga/gradle/paket/PaketIntegrationBaseSpec.groovy, src/integrationTest/groovy/wooga/gradle/paket/pack/PaketPackIntegrationSpec.groovy, src/main/groovy/wooga/gradle/paket/pack/PaketPackPlugin.groovy, src/test/groovy/wooga/gradle/paket/pack/PaketPackPluginSpec.groovy
Each paket.template file in the file tree is spawning a new `PaketPack`
task. This commit handles situation when multiple paket.template files
with the same `id` are location in the file tree.
The plugin will only create one task and skips any other task creation
if a pack task with the same name was already created.
=> Fix plugin crash when duplicate paket.template ids in file tree

.gitignore, .travis.yml, src/integrationTest/groovy/wooga/gradle/paket/pack/PaketPackIntegrationSpec.groovy, src/main/groovy/wooga/gradle/paket/base/tasks/AbstractPaketTask.groovy, src/main/groovy/wooga/gradle/paket/pack/PaketPackPlugin.groovy, src/main/groovy/wooga/gradle/paket/pack/PaketPublishingArtifact.groovy, src/main/groovy/wooga/gradle/paket/pack/tasks/PaketPack.groovy, travis/setup_linux.sh
The project version had to be set before the plugin gets applied.
This commit will bind the version property lazy. The version gets
evaluated at execution time.
=> Fix lazy project version

.gitignore, Jenkinsfile, src/integrationTest/groovy/wooga/gradle/paket/publish/PaketPublishIntegrationSpec.groovy, src/main/groovy/wooga/gradle/paket/pack/PaketPackPlugin.groovy, src/main/groovy/wooga/gradle/paket/publish/PaketPublishPlugin.groovy, src/main/groovy/wooga/gradle/paket/publish/repository/NugetRepository.groovy, src/main/groovy/wooga/gradle/paket/publish/tasks/PaketCopy.groovy, src/test/groovy/wooga/gradle/paket/pack/PaketPackPluginSpec.groovy, src/test/groovy/wooga/gradle/paket/publish/repository/NugetRepositorySpec.groovy
Add a set of tasks to publish `nupkg` package to a local destination. This helps when developing new features and you want to test them in other projects (PuzzleCore use case).
**How to set it up:**
```
publishing {
repositories {
nuget {
name "snapshot"
url "https://wooga.jfrog.io/wooga/api/nuget/atlas-nuget-snapshot"
}
nuget {
name "rc"
url "https://wooga.jfrog.io/wooga/api/nuget/atlas-nuget-rc"
}
nuget {
name "final"
url "https://wooga.jfrog.io/wooga/api/nuget/atlas-nuget-release"
}
nuget {
name "localExportOne"
path "../myOtherProject"
}
nuget {
name "localExportTwo"
path "../myLocalNugetStorage"
}
}
}
```
You have to set a `path` instead of `url` 
This generates a new set of tasks:
```
publishLocal - publish all nupkg to all local paths
publishLocallocalExportOne - Publishes all …
```
=> Add publishLocal tasks

src/integrationTest/groovy/wooga/gradle/paket/get/PaketInstallIntegrationSpec.groovy, src/integrationTest/groovy/wooga/gradle/paket/unity/PaketUnityIntegrationSpec.groovy, src/main/groovy/wooga/gradle/paket/unity/PaketUnityPlugin.groovy
we discovered a bug where `paketUnityInstall`doesn't get called after `paketUpdateMyDependencyName`. 
This fix ensures `paketUnityInstall` to be called after every call to `paketUpdateMyDependencyName`
Fixes #12
=> Attach paketUnityInstall task to all relevant tasks

build.gradle, gradle/wrapper/gradle-wrapper.properties, src/main/groovy/wooga/gradle/paket/base/tasks/AbstractPaketTask.groovy
Update buildgradle to use `net.wooga.plugins` plugin. This limits down
the basic configuration for development.
Use gradle `4.0` for development
resolves #16 
[IOS]:http://resources.atlas.wooga.com/icons/icon_iOS.svg "iOS" …
=> Update Project setup

src/main/groovy/wooga/gradle/paket/base/PaketPluginExtension.groovy, src/main/groovy/wooga/gradle/paket/base/internal/DefaultPaketPluginExtension.groovy, src/main/groovy/wooga/gradle/paket/unity/PaketUnityPluginExtension.groovy, src/main/groovy/wooga/gradle/paket/unity/internal/DefaultPaketUnityPluginExtension.groovy
Just a small refactor to keep the API clean. The paketUnity extension
implemented a new getter `getLockFile`. It makes more sense to move this
property to the base class/interface `PaketPluginExtension`. …
=> Move getLockfile getter to PaketPluginExtension

docs/Publish.md, src/integrationTest/groovy/wooga/gradle/paket/publish/PaketPublishIntegrationSpec.groovy, src/main/groovy/wooga/gradle/paket/publish/PaketPublishPlugin.groovy, src/main/groovy/wooga/gradle/paket/publish/repository/NugetArtifactRepository.groovy, src/main/groovy/wooga/gradle/paket/publish/repository/internal/NugetRepository.groovy, src/main/groovy/wooga/gradle/paket/publish/tasks/PaketPush.groovy, src/test/groovy/wooga/gradle/paket/publish/repository/NugetRepositorySpec.groovy
Description
===========
Paket push supports a custom `--endpoint` or `endpoint` flag for the
`push command. This pull requests adds support for this option.
The task `PaketPush` contains a new property endpoint which
when sets adds this argument to the `paket push` command.
The Nuget Repository object also contains a new setter for `endpoint`
this allows to configure the endpoint at publish repository level.
```groovy
publishing {
repositories {
nuget {
name "nuget1"
url "https://nuget.feed"
endpoint "/api/v2/package"
}
}
}
```
resolves #24 
Changes
======= …
=> Add endpoint input value to PaketPush

src/main/groovy/wooga/gradle/paket/pack/PaketPackPlugin.groovy, src/main/groovy/wooga/gradle/paket/pack/internal/PaketPublishingArtifact.groovy, src/main/groovy/wooga/gradle/paket/pack/tasks/PaketPack.groovy
Description
===========
The internal usage of `packageID` property was confusing. This pr
changes the handling of `packageID` provided by `paket.template`
resolves #23 
Changes
======= …
=> Refactor PaketPack task properties

src/integrationTest/groovy/wooga/gradle/paket/PaketIntegrationArgumentsSpec.groovy, src/integrationTest/groovy/wooga/gradle/paket/PaketIntegrationBaseSpec.groovy, src/integrationTest/groovy/wooga/gradle/paket/get/PaketGetArgumentsSpec.groovy, src/integrationTest/groovy/wooga/gradle/paket/pack/PaketPackArgumentsSpec.groovy, src/main/groovy/wooga/gradle/paket/base/tasks/internal/AbstractPaketTask.groovy
This pull request adds changes to allow all possible additional paket
command switches be set through the gradle tasks. The most important
switches are implemented already within the task interface. But some
optional switches are not. We don't want to add a big support list of
all possible commandline options at the time, the users of the tasks can
configure these options themself. …
=> Expose args property from AbstractPaketTask to all tasks

src/integrationTest/groovy/wooga/gradle/paket/pack/PaketPackIntegrationSpec.groovy, src/main/groovy/wooga/gradle/paket/pack/tasks/PaketPack.groovy
This change makes it possible to set the `version` parameter in the task `PaketPack` as a lazy value (`Closure`, eg `Callable`).
* ![FIX] version parameter in `PaketPack`
resolves #31  …
=> Fix set of lazy version parameter for paketPack

README.md, gradle_check_versions.sh, src/integrationTest/groovy/wooga/gradle/paket/IntegrationSpec.groovy, src/integrationTest/groovy/wooga/gradle/paket/PaketIntegrationArgumentsSpec.groovy, src/integrationTest/groovy/wooga/gradle/paket/PaketIntegrationBaseSpec.groovy, src/main/groovy/wooga/gradle/paket/base/internal/DefaultPaketPluginExtension.groovy
This pull requests adds a simple test script to check with the help of
integration tests which Gradle version works. I also did some changes in
the test setup to make these tests possible. …
=> Update list of supported gradle versions

src/integrationTest/groovy/wooga/gradle/paket/IntegrationSpec.groovy, src/integrationTest/groovy/wooga/gradle/paket/PaketIntegrationBaseSpec.groovy
We constantly hit a rate limit when running the integration tests for this gradle plugin. I don't want to bundle _Paket_ resources with this plugin and also no special test setup or logic execute during the tests. This is why I implemented a cache for each test spec. We run roughly 110 test features and each time we download the paket resources. The new test logic hooks itself into the `cleanup` method for each spec and copies the generated `.paket` folder to a temp directory. Another hook in `setup` phase will check if the paket resources are available in this temp folder and copy it before execution. This means no code duplication for downloading the resources and no adjustments to the base plugin code. If for whatever reason the cache directory is empty the test code will download the …
=> Cache paket.bootstrapper.exe and paket.exe during integration tests

src/integrationTest/groovy/wooga/gradle/paket/base/PaketBaseIntegrationSpec.groovy, src/integrationTest/groovy/wooga/gradle/paket/get/PaketInstallIntegrationSpec.groovy, src/integrationTest/groovy/wooga/gradle/paket/get/PaketRestoreIntegrationSpec.groovy, src/main/groovy/wooga/gradle/paket/base/PaketBasePlugin.groovy, src/main/groovy/wooga/gradle/paket/get/tasks/PaketRestore.groovy
We defined the `UP-TO-DATE` spec as always false for testing reasons in the past. This pull requests adds tests and `upToDateWhen` specs to mimic `paket restore`'s own update check.
This pull request brings also a change in the paket base plugin. Paket base will apply the `LifecycleBase` plugin to be able to adjust the `clean` task. The `clean` task will delete all paket generated directories: `.paket`, `packages` and `paket-files`.
resolves #34  …
=> Update paket restore UP-TO-DATE handling and clean pattern

src/main/groovy/wooga/gradle/paket/unity/tasks/PaketUnityInstall.groovy
The new paket unity implementation is excluding __.meta__ files. This
pull requests adds these files back to be copied. Also adjusts the log
level for the unity install task.
[IOS]:http://resources.atlas.wooga.com/icons/icon_iOS.svg "iOS" …
=> Fix exclude pattern for PaketUnityInstall task

src/main/groovy/wooga/gradle/paket/base/utils/internal/PaketLock.groovy, src/test/groovy/wooga/gradle/paket/base/utils/internal/PaketLockSpec.groovy
The `paket.lock` file parser has issues with counting leading whitespaces. The value from the old logic `def newLeadingWhitespaces =(line =~ /\s/).size()` returns the number of all white space characters in the current line.
The second part:
```groovy
if (newLeadingWhitespaces > currentLeadingWhitespaces) {
currentIndent++
} else if (newLeadingWhitespaces < currentLeadingWhitespaces) {
currentIndent--
}
```
didn't take into account when the indention level suddenly jumped from 3 to 1. I also made the method `List<String> getAllDependencies(List<String> references)` recursive. I added a new test covering the failing behavior …
=> Fix paket.lock file parser

Jenkinsfile, src/integrationTest/groovy/wooga/gradle/extensions/GradleIntegrationSpecInterceptor.groovy, src/integrationTest/groovy/wooga/gradle/extensions/PaketDependencySetupExtension.groovy, src/integrationTest/groovy/wooga/gradle/extensions/PaketUnitySetup.groovy, src/integrationTest/groovy/wooga/gradle/extensions/PaketUnitySetupExtension.groovy, src/integrationTest/groovy/wooga/gradle/paket/unity/PaketUnityChangeSpec.groovy
This patch moves some boilerplate setup code into custom spock
extensions. This patch adds two extensions that provide a clean
interface for testing paket and paket unity project integrations:
* @PaketDependency
* @PaketUnity
Is a resource extension which setups a paket project.
It will create a `paket.dependendies` along with a `paket.lock` file and
stub `cs` files in `packages` directory. This extensions should be
updated for future use in other tests (don't create a lock file,
specify sources, etc).
```java
@ExtensionAnnotation(PaketDependencySetupExtension)
@interface PaketDependency {
String[] projectDependencies() default []
}
```
```groovy
class ASpec extends IntegrationSpec {
@PaketDependency(projectDependencies = ["D1", "D2", "D3"])
PaketDependencySetup paketSetup
```
The …
=> Refactor integration spec for paket unity change specs

src/integrationTest/groovy/wooga/gradle/paket/get/PaketRestoreIntegrationSpec.groovy, src/integrationTest/groovy/wooga/gradle/paket/unity/PaketUnityFrameworksSpec.groovy, src/main/groovy/wooga/gradle/paket/unity/tasks/PaketUnityInstall.groovy
This patch fixes an issue with `paketUnityInstall` which only installs
`*.dll` dependencies from nuget when these are located in a framework
directory.
```
packages/Dependency/libs/net35/dep.dll
vs
packages/Dependency/libs/dep.dll
```
This patch just adds a simple rule to also copy these `dll` files over. …
=> Fix dependency installation with missing framework specification

src/integrationTest/groovy/wooga/gradle/paket/PaketIntegrationBaseSpec.groovy, src/integrationTest/groovy/wooga/gradle/paket/base/PaketBaseIntegrationSpec.groovy, src/integrationTest/groovy/wooga/gradle/paket/get/PaketRestoreIntegrationSpec.groovy, src/main/groovy/wooga/gradle/paket/base/PaketBasePlugin.groovy, src/main/groovy/wooga/gradle/paket/base/tasks/PaketBootstrap.groovy
Gradle tends to invalidate it's buildcache whenever it is unclear who produced specific task outputs. This leads to a lot of redownload requests for the paket.exe during tests. This patch adds a custom `upToDateWhen` spec which checks if the paket.exe is available and if the version is the correct one. I have to invoke the tool once because it's the fastest cross platform solution.
* ![IMPROVE] paket.exe caching …
=> Improve paket.exe caching

src/integrationTest/groovy/wooga/gradle/paket/unity/PaketUnityIntegrationSpec.groovy, src/main/groovy/wooga/gradle/paket/unity/PaketUnityPlugin.groovy, src/main/groovy/wooga/gradle/paket/unity/PaketUnityPluginExtension.groovy, src/main/groovy/wooga/gradle/paket/unity/internal/AssemblyDefinitionFileStrategy.groovy, src/main/groovy/wooga/gradle/paket/unity/internal/DefaultPaketUnityPluginExtension.groovy, src/main/groovy/wooga/gradle/paket/unity/tasks/PaketUnityInstall.groovy
Adds a property to the paketUnity plugin that allows including assembly definition files on a paket install.
* ![IMPROVE] PaketUnityPlugin
* ![IMPROVE] PaketUnityInstall
* ![IMPROVE] ASsemblyDefinitionFileStrategy
[ADD]:https://atlas-resources.wooga.com/icons/icon_add.svg "Add"
[IMPROVE]:https://atlas-resources.wooga.com/icons/icon_improve.svg "IMPROVE"
[CHANGE]:https://atlas-resources.wooga.com/icons/icon_change.svg "Change"
[FIX]:https://atlas-resources.wooga.com/icons/icon_fix.svg "Fix"
[UPDATE]:https://atlas-resources.wooga.com/icons/icon_update.svg "Update"
[BREAK]:https://atlas-resources.wooga.com/icons/icon_break.svg "Remove"
[REMOVE]:https://atlas-resources.wooga.com/icons/icon_remove.svg "Remove" …
=> Add option to include assembly definition files for paketInstall

src/main/groovy/wooga/gradle/paket/unity/internal/DefaultPaketUnityPluginExtension.groovy
Fixes missing default value for the includeAssemblyDefinitions property.
* ![FIX] DefaultPaketUnityPluginExtension: Set default for includeAssemblyDefinitions property
[ADD]:https://atlas-resources.wooga.com/icons/icon_add.svg "Add"
[IMPROVE]:https://atlas-resources.wooga.com/icons/icon_improve.svg "IMPROVE"
[CHANGE]:https://atlas-resources.wooga.com/icons/icon_change.svg "Change"
[FIX]:https://atlas-resources.wooga.com/icons/icon_fix.svg "Fix"
[UPDATE]:https://atlas-resources.wooga.com/icons/icon_update.svg "Update"
[BREAK]:https://atlas-resources.wooga.com/icons/icon_break.svg "Remove"
[REMOVE]:https://atlas-resources.wooga.com/icons/icon_remove.svg "Remove"
[IOS]:https://atlas-resources.wooga.com/icons/icon_iOS.svg "iOS" …
=> Fix missing default value for includeAssemblyDefinitions

src/main/groovy/wooga/gradle/paket/base/utils/internal/PaketUnityReferences.groovy, src/test/groovy/wooga/gradle/paket/base/utils/internal/PaketUnityReferencesSpec.groovy
Ensures items parsed in paket unity refs are trimmed.
* ![FIX] PaketUnityReferences
[BREAK]:    https://resources.atlas.wooga.com/icons/icon_break.svg "Remove"
[REMOVE]:   https://resources.atlas.wooga.com/icons/icon_remove.svg "Remove"
[IOS]:      https://resources.atlas.wooga.com/icons/icon_iOS.svg "iOS"
[ANDROID]: …
=> Make sure items in paket references are trimmed

build.gradle, gradle/wrapper/gradle-wrapper.properties, gradle_check_versions.sh, src/integrationTest/groovy/wooga/gradle/paket/unity/PaketUnityChangeSpec.groovy, src/integrationTest/groovy/wooga/gradle/paket/unity/PaketUnityIntegrationSpec.groovy, src/main/groovy/wooga/gradle/paket/base/PaketBasePlugin.groovy, src/main/groovy/wooga/gradle/paket/base/dependencies/internal/DefaultPaketDependencyConfiguration.groovy, src/main/groovy/wooga/gradle/paket/base/dependencies/internal/DefaultPaketDependencyConfigurationContainer.groovy, src/main/groovy/wooga/gradle/paket/base/repository/internal/DefaultNugetArtifactRepository.groovy, src/main/groovy/wooga/gradle/paket/base/repository/internal/DefaultNugetArtifactRepositoryHandlerConvention.groovy, src/main/groovy/wooga/gradle/paket/base/tasks/DownloadPaketBootstrapper.groovy, src/main/groovy/wooga/gradle/paket/base/tasks/PaketBootstrap.groovy, src/main/groovy/wooga/gradle/paket/base/tasks/internal/AbstractPaketTask.groovy, src/main/groovy/wooga/gradle/paket/base/utils/internal/PaketUnityReferences.groovy, src/main/groovy/wooga/gradle/paket/pack/PaketPackPlugin.groovy, src/main/groovy/wooga/gradle/paket/publish/repository/internal/NugetRepository.groovy, src/main/groovy/wooga/gradle/paket/unity/PaketUnityPlugin.groovy, src/main/groovy/wooga/gradle/paket/unity/PaketUnityPluginExtension.groovy, src/main/groovy/wooga/gradle/paket/unity/internal/AssemblyDefinitionFileStrategy.groovy, src/main/groovy/wooga/gradle/paket/unity/internal/DefaultPaketUnityPluginExtension.groovy, src/main/groovy/wooga/gradle/paket/unity/tasks/PaketUnityInstall.groovy, src/test/groovy/wooga/gradle/paket/base/utils/internal/PaketUnityReferencesSpec.groovy
This patch upgrades the whole plugin to be based on gradle 6.8.3. It will not be aimed to be backwards compatible with gradle older than version `5.0`.
* ![UPDATE] ![GRADLE] to version `6.8.3`
* ![BREAK] ![GRADLE] supported backwards compatibility
[BREAK]:    https://resources.atlas.wooga.com/icons/icon_break.svg "Remove"
[REMOVE]: …
=> Upgrade plugin to gradle 6.8.3

Jenkinsfile, build.gradle, src/integrationTest/groovy/wooga/gradle/paket/IntegrationSpec.groovy
atlas plugin gradle plugin updated to 2.2.0, and added Sonarqube support on Jenkinsfile.
* ![UPDATE] `atlas-plugin` gradle plugin to `2.2.0`
* ![NEW] Sonarqube project being uploaded on Jenkinsfile execution
[NEW]:https://resources.atlas.wooga.com/icons/icon_new.svg "New" …
=> Updated atlas plugin to 2.2.0

Jenkinsfile, build.gradle, settings.gradle, src/integrationTest/groovy/wooga/gradle/paket/PaketIntegrationBaseSpec.groovy, src/integrationTest/groovy/wooga/gradle/paket/base/PaketBaseIntegrationSpec.groovy, src/integrationTest/groovy/wooga/gradle/paket/get/PaketInstallIntegrationSpec.groovy, src/integrationTest/groovy/wooga/gradle/paket/get/PaketRestoreIntegrationSpec.groovy, src/integrationTest/groovy/wooga/gradle/paket/pack/PaketPackIntegrationSpec.groovy, src/integrationTest/groovy/wooga/gradle/paket/publish/PaketPublishIntegrationSpec.groovy, src/main/groovy/wooga/gradle/paket/unity/tasks/PaketUnityInstall.groovy
This patch adds snyk monitoring to the build pipeline. It will hook itself into the check and publish stages.
The patch also sets a dependency helper plugin net.wooga.cve-dependency-resolution which applies overrides for dependencies with know fixes for security issues.
* ![ADD] `snyk` monitoring
* ![ADD] `net.wooga.snyk-wdk-java` snyk convention plugin
* ![ADD] `net.wogoa.cve-dependency-resolution` plugin …
=> Add snyk integration [ATLAS-701]

src/integrationTest/groovy/wooga/gradle/paket/get/PaketInstallIntegrationSpec.groovy, src/integrationTest/groovy/wooga/gradle/paket/unity/PaketUnityChangeSpec.groovy, src/main/groovy/wooga/gradle/paket/unity/PaketUnityPlugin.groovy, src/main/groovy/wooga/gradle/paket/unity/PaketUnityPluginConventions.groovy, src/main/groovy/wooga/gradle/paket/unity/internal/AssemblyDefinitionFileStrategy.groovy, src/main/groovy/wooga/gradle/paket/unity/tasks/PaketUnityInstall.groovy
When one initially includes assembly definitions but then disables it and runs `paketInstall`, the cache won't be updated properly, thus the assembly definitions won't be removed when they should be.
The issue ended up being due to the `AssemblyDefinitionFileStrategy` being set to `manual`, which made the asmdef files being ignored during the output directory cleanup (thus not deleted). Instead it has been set to `disabled`, leading to expected behaviour.
* ![FIX] `includeAssemblyDefinitions` up-to-date check, by disabling the assembly file definition strategy
[CHANGE]: …
=> Fix the issue when switching includeAssemblyDefinitions

Jenkinsfile, build.gradle, docs/Unity.md, src/integrationTest/groovy/wooga/gradle/paket/unity/PaketUnityIntegrationSpec.groovy, src/integrationTest/groovy/wooga/gradle/paket/unity/fixtures/PaketFixtures.groovy, src/main/groovy/wooga/gradle/paket/unity/PaketUnityPlugin.groovy, src/main/groovy/wooga/gradle/paket/unity/PaketUnityPluginConventions.groovy, src/main/groovy/wooga/gradle/paket/unity/PaketUnityPluginExtension.groovy, src/main/groovy/wooga/gradle/paket/unity/PaketUpmPackageSpec.groovy, src/main/groovy/wooga/gradle/paket/unity/internal/DefaultPaketUnityPluginExtension.groovy, src/main/groovy/wooga/gradle/paket/unity/internal/UPMPaketPackage.groovy, src/main/groovy/wooga/gradle/paket/unity/tasks/PaketUnityInstall.groovy, src/main/resources/package.json.template
Paket packages can now be configured to be installed as UPM packages. This can be useful when your paket package contains an UPM one (with a `package.json` file), and you want it to be integrated with Unity's packages folder.
This mode sets the installation directory (`paketOutputDirectoryName`) to the unity project's `Packages` folder, and ensures that the `package.json`file for each dependency is in the installed package root.
If an installed package is not UPM-compatible, that is, it doesn't have a `package.json` file, such file will be created. By default, a `package.json` is generated with `com.wooga.nuget.${paketPackage.toLowerCase()}` name, and version `0.0.0`,  but those can be overridden and more properties can be added on using the mappings in `paketUpmPacakgeJson`. 
UPM mode …
=> Add paket-unity UPM mode [ATLAS-1273]

src/main/groovy/wooga/gradle/paket/unity/PaketUnityPlugin.groovy, src/main/groovy/wooga/gradle/paket/unity/PaketUnityPluginConventions.groovy
Adds `PAKET_UNITY_ENABLE_UPM_PACKAGE` boolean environment variable to determine if paket packages should be installed like UPM packages or not. This feature was already present in the `paketUpmPackageEnabled` extension variable.
* ![ADD] PAKET_UNITY_ENABLE_UPM_PACKAGE environment variable
[BREAK]: …
=> Add PAKET_UNITY_ENABLE_UPM_PACKAGE env var

src/main/groovy/wooga/gradle/paket/base/tasks/PaketBootstrap.groovy
Fixes a bug detected in UBS, where gradle deletes the `paket.bootstrap.exe` file generated by the `DownloadPaketBootstraper`.
You can reproduce the issue by calling:
```sh
gradlew paketBootstrap #this should run correctly
rm -r .paket
gradlew paketBootstrap #this should fail, accusing that the `paket.bootstrap.exe` file doesn't exists.
```
Several tests pointed out that the file is correctly downloaded, but just disappears between the `DownloadPaketBootstraper` and `PaketBootstrap` tasks. This happens because  its set as an output of `PaketBootstrap`. Then in some conditions, gradle wipes out the file, likely to make room to some intended output, making the `PaketBoostrap` task fail. Removing the bootstrap executable from the outputs of `PaketBootstrap` solves the issue, and does not …
=> Removes paket bootstrap executable from PaketBootstrap task outputs

src/main/groovy/wooga/gradle/paket/unity/PaketUnityPluginExtension.groovy, src/main/groovy/wooga/gradle/paket/unity/internal/DefaultPaketUnityPluginExtension.groovy
This just adds an additional way of setting/getting the preinstalled upm packages in the plugin extension using providers.
* ![ADD] add provider-based API for set/get PreInstalledUpmPackages
[BREAK]:    https://resources.atlas.wooga.com/icons/icon_break.svg "Remove"
[REMOVE]:   https://resources.atlas.wooga.com/icons/icon_remove.svg "Remove"
[IOS]: …
=> Adds provider API for preinstalledUpmPacakges [ATLAS-1463]

src/integrationTest/groovy/wooga/gradle/paket/unity/PaketUnityFrameworksSpec.groovy, src/main/groovy/wooga/gradle/paket/base/internal/DefaultPaketPluginExtension.groovy, src/main/groovy/wooga/gradle/paket/base/tasks/PaketDependenciesTask.groovy, src/main/groovy/wooga/gradle/paket/base/utils/internal/PaketDependencies.groovy, src/main/groovy/wooga/gradle/paket/get/tasks/PaketInstall.groovy, src/main/groovy/wooga/gradle/paket/get/tasks/PaketOutdated.groovy, src/main/groovy/wooga/gradle/paket/get/tasks/PaketRestore.groovy, src/main/groovy/wooga/gradle/paket/get/tasks/PaketUpdate.groovy, src/main/groovy/wooga/gradle/paket/pack/tasks/PaketPack.groovy, src/main/groovy/wooga/gradle/paket/publish/tasks/PaketPush.groovy, src/main/groovy/wooga/gradle/paket/unity/PaketUnityPluginConventions.groovy, src/test/groovy/wooga/gradle/paket/base/utils/internal/PaketDependenciesSpec.groovy
Add support for `netstandard2.0` as a default framework. Update comments on the tasks for a bit more clarity.
* ![UPDATE] Default framework versions, removing deprecated unity-specific ones, now bringing NET Standard 2.
* ![IMPROVE] Comments on the tasks
[BREAK]:    https://resources.atlas.wooga.com/icons/icon_break.svg "Remove"
[REMOVE]: …
=> Update the default supported frameworks used
